sudo: required
dist: trusty
services:
- docker
before_install:
- docker pull cannin/latex
- docker run -t -v /home/travis/build/cannin/process-descriptions:/latex -w /latex
  cannin/latex /bin/sh -c ". /etc/environment && pdflatex --version && ls -l /latex"
script:
- docker run -t -v /home/travis/build/cannin/process-descriptions:/latex -w /latex
  cannin/latex /bin/sh -c ". /etc/environment && apt-get -qq update && sudo apt-get
  install -y --no-install-recommends inkscape && cd /latex/Specification && make"
- chmod +x deploy.sh && ./deploy.sh
deploy:
  provider: releases
  file:
  - Specification/sbgn_PD-level1.pdf
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- ./deploy.sh
env:
  global:
  - GITHUB_REPO: cannin/process-descriptions
  - secure: a15kyqGJiAbvz4eb2XvzV8jjep4IXUMg7REkPUgstm+cj+kX7qZaKLqTp916MJZnp9Z01FXRJJa6BflTekMlPPGScQZJKu8irjAxou6fxpXJwlEtvWS9Ci5XjIyk21zg6Em/+ANfGeVGDsoKPz1wnJ9Mg37qE5V1IZhlNfYLg2reskNBBWyFjIzns3Ys7Abi5k2mHAoGRTBX6tDQyRRITxs+zJH/lPrgv+0vkNAfO6UF8DOtxQJSf1msntkkEPzBTcTmivLShWenbS4HURLJYIrodjnLXVk6XCV/XkeraruuXn5mkF0ZjrkZQAJBcFo2FrgbZEXTd5qhSLAeemYP5Bx9x8VVmb61TSNVvHkGuFCn7llVUhxEcRb1WlHpAu1eiJ4MvKMpuBsk7SO0ubUBcO4WqeG8h71TokkU4fCr833dW/P6XAIZaniVw+7NoMy60FYLy1oCI4QmpWiRcTZoC5LvBcW4avRa03mdlkEfUwaJqjLPlifS4SoTPD3lSP8IxihfE19mniNBYoa74E/DN6AmQ8gytoMZATwi6bZ91jH3labsUhp4CpifW0PvNoOXPQPgxkUXiiqVkniDCXZmyoUF/C+xoF1DQ6aSLnSedtigaZkOQ6pqd3QbQCLd/KSD0V8Rvsg62gD+RMA1A/a1NbHv/IT4z3S843piUsGSlho=
  - secure: rz9Ypz0bbfeg14FLZWGhDhnbmp8tdzHsKn3s+11vorNfpRfPB9Dv3cQMsBhHdQmo2FyFKTKaTHY6ie3y2kzg1OLcsjFhb9EvXzApCWfLabV3vvfcuCfMcgTvkXPocWYSUs5dXGUi1yx9S9sZqVkpFBqkFl/MTOIqGcJ6Rrn/93mttWeArwUVqXBbtbIrYZidB9IkVotTJw+3oIddgCUfLPffBuhKPjRHFU51+psnkG3GoW34SbOSP1k1IA9wmIaS9zDRKrpNltamCjpS9Qt5P74Nxu+mzf/ivpeo7afrv0WSbI7Zm2JU7s0vXewu3Bajs1opigZXZgKVu8HHeYMVw5B3YfPuS3uh++uMbRCD+3dQP8b94/GDx4RpYK0Wm6GjGXmzN7ECNZoGGUcTu/KJYkukHHgB2oLJK3RLTJTtXmpmmTYvlK5x29hAPJE7glEFCjWxhcGaHo0dBu3kArIYSNDVXEqhW5mm21UqzG0J3mfkNFhnPnMQmCzCQpSRNSFim3Whi7syGX0SxO8c2wMOX9CcUcahdAUinhlZaBFxos/yDmP67AiZWTP4z8Z5hFg4064fnskuCAMi9lD3I2iJ1Htv39C8+QE2iqtFmdkE6kblbb69U07nRMV4LW6+VVmnPyJ+9KK/cYNzN1fB2CgTnS86ZsaxVNz2Skk4PksQ2m4=
