sudo: required
dist: trusty
services:
- docker
script:
- echo "4O4GitHub Pes plachlder" > index.html
after_success:
- git clone https://${GH_TOKEN}@github.com/cannin/process-descriptions.git
  tmp
- git config --global push.default simple && git config --global user.name "fake"
  && git config --global user.email "fake@fake.com"
- cd tmp && mkdir travis && cp index.html travis
- git add . && git commit -m "T3"
- git remote set-url origin https://${GH_TOKEN}@github.com/cannin/process-descriptions.git
- git push origin master
env:
  global:
  - GITHUB_REPO: cannin/process-descriptions
  - secure: KcKTj9j574ZFY//V+03yigQgtrxHq67+BKpqRHBLzOGY2QhsEfYb+AzhXPFWKc3lh7b2r6vSBiurhAR8TiseRCcbtVw0Z1d+ReOMNmCTDegCT1hP4s2LI0ZAI6yUHx5Vv1SuWNMIbx1OB0vhhkh7OzmbNe8a1mrhWCdPCV4pvqDmY2HdBoArZF4jjKXqlIM6/6qxGHg10NsgbrN7ahSlGHWE+4DzpVp+Fyxks2Nl5Iwuv9COt+Qf9r+cDhBCK/giHuWiS2BlAuqPQDCp3j0d8wYJcpzHyLGQBYvN+r5GeC8g6CtoRGYyKJoGQJStT19eS45EUha0PTmTOqzTtgiuey+GMqGpY/tAiVMd6AHieEnqFpIPh1vC0cnFW5we5lW2fxPEmagkfeN5PA8gp6VR1o+tNIpS0z7y2uGLHDO6ZR2oiI9d57SRHbWsiAF8OWiGGNI094n7+P9FdGRHapMx7M9q+WeOtO5gpYRxqfE/jy/+TcX6KZXi9npLsw6KqlS/NfJgkoWdax6yY8G8rt3VAeKggvOrbSdHWQ9BQ5ITzkTbIDqpVnv83daU1lcjRE7nQPROQRi0g5dgEdJLNZ4St4rLwyEEz+D+K2gwy26H2iDYfd+vmdMzpb1lc/RvqQe6sz1wV8gKRUy2F2uO3A9KUdH+5X6g2VGB5q9KE3+2nWs=
